export const TOGGLE_DISPLAY_FORM = 'TOGGLE_DISPLAY_FORM';

export const TOGGLE_DISPLAY_LIST = 'TOGGLE_DISPLAY_LIST';

export const HIDE_DISPLAY_FORM = 'HIDE_DISPLAY_FORM';

export const HIDE_DISPLAY_LIST = 'HIDE_DISPLAY_LIST';

export const RESET_BUTTON_TO_DEFAULT = 'RESET_BUTTON_TO_DEFAULT';

export const ADD_OR_UPDATE_FLAVOR = 'ADD_OR_UPDATE_FLAVOR';

export const DELETE_FLAVOR = 'DELETE_FLAVOR';

export const FLAVOR_DETAILS = 'FLAVOR_DETAILS';

export const RESET_SELECTED_FLAVOR = 'RESET_SELECTED_FLAVOR';

export const DECREMENT_SERVINGS = 'DECREMENT_SERVINGS';

export const ANNOUNCE_OUT_OF_STOCK = 'ANNOUNCE_OUT_OF_STOCK';